<script setup lang="ts">
import { computed, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { Search, ArrowRight, CopyDocument, Refresh } from '@element-plus/icons-vue'; import { publicApi } from '@/api/public'; import { ApiError } from '@/lib/http'; import type { PublicTrace } from '@/types/domain'; import TraceHero from '@/components/trace/TraceHero.vue'; import TraceSummary from '@/components/trace/TraceSummary.vue'; import TraceChain from '@/components/TraceChain.vue'; import TraceTemperature from '@/components/trace/TraceTemperature.vue'; import TraceCertificates from '@/components/trace/TraceCertificates.vue'; import EmptyState from '@/components/EmptyState.vue'
const route = useRoute(); const router = useRouter(); const traceCode = ref(String(route.params.traceCode || '')); const loading = ref(false); const trace = ref<PublicTrace>(); const state = ref<'idle' | 'ready' | 'not-found' | 'error'>('idle')
const hasTrace = computed(() => state.value === 'ready' && trace.value)
async function search() { if (!traceCode.value.trim()) return ElMessage.warning('请输入溯源码'); loading.value = true; try { trace.value = await publicApi.trace(traceCode.value.trim()); state.value = 'ready'; router.replace(`/trace/${encodeURIComponent(traceCode.value.trim())}`) } catch (error) { trace.value = undefined; state.value = error instanceof ApiError && error.code === 3001 ? 'not-found' : 'error' } finally { loading.value = false } }
async function copy() { if (trace.value?.traceCode) { await navigator.clipboard?.writeText(trace.value.traceCode); ElMessage.success('溯源码已复制') } }
if (traceCode.value) search()
</script>
<template><div class="trace-view"><TraceHero :trace-code="trace?.traceCode" :product-variety="trace?.productVariety" :retailer-name="trace?.retailerName" :sale-store="trace?.saleStore" /><section class="trace-search"><div class="trace-search__copy"><span class="eyebrow">LOOK UP A PRODUCT</span><h2>输入溯源码，查询产品旅程</h2><p>溯源码通常位于产品包装或电子凭证上。</p></div><div class="trace-search__form"><el-input v-model="traceCode" size="large" placeholder="例如 FSTS-20260921-SH-0001" @keyup.enter="search"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-button type="primary" size="large" :loading="loading" :icon="ArrowRight" @click="search">查询溯源</el-button></div></section><section v-if="hasTrace" class="trace-result"><TraceSummary :trace="trace!" /><div class="trace-result__grid"><div class="trace-result__main"><section class="trace-section"><div class="trace-section__head"><div><span class="eyebrow">TRACE CHAIN</span><h3>全链路流转</h3></div><el-button text :icon="CopyDocument" @click="copy">复制溯源码</el-button></div><TraceChain :links="trace!.links" /></section><TraceTemperature :points="trace!.temperatureCurve || []" /></div><aside class="trace-result__side"><TraceCertificates :links="trace!.links" /><section class="trace-section trace-note"><span class="eyebrow">TRUST NOTE</span><h3>数据可信说明</h3><p>链路信息来自参与流通的节点企业，由系统在交接确认时记录。展示内容仅用于产品溯源查询。</p><div class="trace-note__seal">FSTS VERIFIED <small>可信冷链记录</small></div></section></aside></div></section><section v-else-if="state === 'idle'" class="trace-placeholder"><div class="trace-placeholder__number">01</div><h3>从一串码开始</h3><p>查询后，这里会展示产品批号、流转企业、温度记录和检验证明。</p></section><section v-else class="trace-placeholder trace-placeholder--error"><div class="trace-placeholder__number">!</div><h3>{{ state === 'not-found' ? '没有找到这串溯源码' : '暂时无法查询' }}</h3><p>{{ state === 'not-found' ? '请检查输入是否完整，或向销售方确认溯源码。' : '服务正在恢复，请稍后重试。' }}</p><el-button :icon="Refresh" @click="search">重新查询</el-button></section></div></template>
