<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { Search, ArrowRight, CopyDocument, Refresh, Camera, Download, Link } from '@element-plus/icons-vue'; import { publicApi } from '@/api/public'; import { ApiError } from '@/lib/http'; import { extractTraceCode } from '@/lib/traceCode'; import { useTraceLinkBase } from '@/composables/useTraceLinkBase'; import type { PublicTrace } from '@/types/domain'; import TraceHero from '@/components/trace/TraceHero.vue'; import TraceSummary from '@/components/trace/TraceSummary.vue'; import TraceChain from '@/components/TraceChain.vue'; import TraceTemperature from '@/components/trace/TraceTemperature.vue'; import TraceCertificates from '@/components/trace/TraceCertificates.vue'; import TraceQrCode from '@/components/TraceQrCode.vue'; import QrScanDialog from '@/components/QrScanDialog.vue'
const route = useRoute(); const router = useRouter(); const { detect, link } = useTraceLinkBase(); const traceCode = ref(String(route.params.traceCode || '')); const loading = ref(false); const trace = ref<PublicTrace>(); const state = ref<'idle' | 'ready' | 'not-found' | 'error'>('idle'); const scanVisible = ref(false); const qrRef = ref<InstanceType<typeof TraceQrCode>>()
const hasTrace = computed(() => state.value === 'ready' && trace.value)
// 二维码承载追溯页链接：手机扫它就能直接打开这一页，链接里已把 localhost 换成局域网地址
const traceLink = computed(() => (trace.value?.traceCode ? link(trace.value.traceCode) : ''))
async function search(source?: string) { const input = (source ?? traceCode.value).trim(); if (!input) return ElMessage.warning('请输入溯源码'); const value = extractTraceCode(input) || input; traceCode.value = value; loading.value = true; try { trace.value = await publicApi.trace(value); state.value = 'ready'; router.replace(`/trace/${encodeURIComponent(value)}`) } catch (error) { trace.value = undefined; state.value = error instanceof ApiError && error.code === 3001 ? 'not-found' : 'error' } finally { loading.value = false } }
async function onDecoded(code: string) { await search(code) }
async function copy(value?: string, tip = '溯源码已复制') { if (value) { await navigator.clipboard?.writeText(value); ElMessage.success(tip) } }
function downloadQr() { qrRef.value?.download(trace.value?.traceCode) }
// 直接改地址栏里的溯源码（例如手机扫码在新标签打开）时同步刷新结果
watch(() => route.params.traceCode, (value) => { const next = String(value || ''); if (next && next !== traceCode.value) { traceCode.value = next; search(next) } })
onMounted(() => { void detect(); if (traceCode.value) search() })
</script>
<template><div class="trace-view"><TraceHero :trace-code="trace?.traceCode" :product-variety="trace?.productVariety" :retailer-name="trace?.retailerName" :sale-store="trace?.saleStore" /><section class="trace-search"><div class="trace-search__copy"><span class="eyebrow">LOOK UP A PRODUCT</span><h2>扫码或输入溯源码，查询产品旅程</h2><p>手机扫描产品包装上的二维码，或直接输入溯源码。</p></div><div class="trace-search__form"><el-input v-model="traceCode" size="large" placeholder="例如 FSTS-20260921-SH-0001" @keyup.enter="search()"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-button type="primary" size="large" :loading="loading" :icon="ArrowRight" @click="search()">查询溯源</el-button><el-button size="large" :icon="Camera" @click="scanVisible = true">扫一扫</el-button></div></section><section v-if="hasTrace" class="trace-result"><TraceSummary :trace="trace!" /><div class="trace-result__grid"><div class="trace-result__main"><section class="trace-section"><div class="trace-section__head"><div><span class="eyebrow">TRACE CHAIN</span><h3>全链路流转</h3></div><el-button text :icon="CopyDocument" @click="copy(trace!.traceCode)">复制溯源码</el-button></div><TraceChain :links="trace!.links" /></section><TraceTemperature :points="trace!.temperatureCurve || []" /></div><aside class="trace-result__side"><section class="trace-section trace-qr-card"><div class="trace-section__head"><div><span class="eyebrow">SCAN TO VERIFY</span><h3>图形化溯源码</h3></div></div><TraceQrCode ref="qrRef" :value="traceLink" :link="traceLink" :code="trace!.traceCode" :size="168" caption="用手机相机或微信扫描这张二维码，即可打开本产品的追溯页" /><div class="trace-qr-card__actions"><el-button :icon="Download" @click="downloadQr">下载二维码</el-button><el-button :icon="Link" @click="copy(traceLink, '追溯链接已复制')">复制链接</el-button></div></section><TraceCertificates :links="trace!.links" /><section class="trace-section trace-note"><span class="eyebrow">TRUST NOTE</span><h3>数据可信说明</h3><p>链路信息来自参与流通的节点企业，由系统在交接确认时记录。展示内容仅用于产品溯源查询。</p><div class="trace-note__seal">FSTS VERIFIED <small>可信冷链记录</small></div></section></aside></div></section><section v-else-if="state === 'idle'" class="trace-placeholder"><div class="trace-placeholder__number">01</div><h3>从一串码开始</h3><p>输入溯源码，或用手机扫描产品包装上的二维码，即可查看批号、流转企业、温度记录和检验证明。</p></section><section v-else class="trace-placeholder trace-placeholder--error"><div class="trace-placeholder__number">!</div><h3>{{ state === 'not-found' ? '没有找到这串溯源码' : '暂时无法查询' }}</h3><p>{{ state === 'not-found' ? '请检查输入是否完整，或向销售方确认溯源码。' : '服务正在恢复，请稍后重试。' }}</p><el-button :icon="Refresh" @click="search()">重新查询</el-button></section><QrScanDialog v-model="scanVisible" title="扫一扫溯源码" @decoded="onDecoded" /></div></template>
