<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import AppLogo from '@/components/AppLogo.vue'
import { ArrowLeft, Fold, Expand, Monitor, SwitchButton } from '@element-plus/icons-vue'
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const collapsed = ref(false); const mobileOpen = ref(false)
const isAdmin = computed(() => auth.role === 'admin')
const nav = computed(() => isAdmin.value ? [{ label: '运营总览', path: '/admin/dashboard', icon: 'DataAnalysis' }, { label: '节点企业', path: '/admin/enterprises', icon: 'OfficeBuilding' }] : [{ label: '产品批号', path: '/enterprise/batches', icon: 'Box' }, { label: '进场确认', path: '/enterprise/confirm-requests', icon: 'CircleCheck' }, { label: '上游数据', path: '/enterprise/upstream', icon: 'Connection' }, { label: '企业资料', path: '/enterprise/profile', icon: 'User' }])
const title = computed(() => String(route.meta.title || '工作台'))
async function logout() { const target = isAdmin.value ? '/admin/login' : '/enterprise/login'; await auth.logout(); router.replace(target) }
</script>
<template>
  <div class="workbench" :class="{ 'is-collapsed': collapsed }"><aside class="sidebar" :class="{ 'is-open': mobileOpen }"><div class="sidebar__top"><AppLogo /><el-button text class="mobile-close" @click="mobileOpen = false"><ArrowLeft /></el-button></div><div class="workspace-chip"><span class="workspace-chip__dot"></span><span>{{ isAdmin ? '系统管理端' : '流通节点端' }}</span></div><nav class="side-nav"><router-link v-for="item in nav" :key="item.path" :to="item.path" class="side-nav__item" active-class="is-active" @click="mobileOpen = false"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span></router-link></nav><div class="sidebar__foot"><router-link to="/trace" class="side-nav__item side-nav__item--muted"><el-icon><Monitor /></el-icon><span>消费者查询</span></router-link></div></aside><div v-if="mobileOpen" class="sidebar-scrim" @click="mobileOpen = false"></div><section class="main-shell"><header class="topbar"><div class="topbar__left"><el-button text class="collapse-btn" @click="collapsed = !collapsed"><Expand v-if="collapsed" /><Fold v-else /></el-button><el-button text class="mobile-menu" @click="mobileOpen = true"><Fold /></el-button><div class="breadcrumbs"><span>FSTS</span><b>/</b><strong>{{ title }}</strong></div></div><div class="topbar__right"><div class="topbar__signal"><span></span>服务正常</div><el-dropdown><button class="identity"><span class="identity__avatar">{{ auth.displayName.slice(0, 1) }}</span><span class="identity__name">{{ auth.displayName }}</span><el-icon><Expand /></el-icon></button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="isAdmin ? router.push('/admin/dashboard') : router.push('/enterprise/profile')">账户设置</el-dropdown-item><el-dropdown-item divided @click="logout"><el-icon><SwitchButton /></el-icon>退出登录</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></header><main class="page-content"><router-view /></main><footer class="app-footer">FSTS 冷链溯源系统 <span>·</span> 数据链路可信，冷链全程可见</footer></section></div>
</template>
